// <auto-generated />
using System;
using GroupCoursework.DatabaseConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GroupCoursework.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
<<<<<<<< HEAD:Migrations/20240503052041_creat tables.Designer.cs
    [Migration("20240503052041_creat tables")]
    partial class creattables
========
    [Migration("20240503041345_create user, blog and blog vote table ")]
    partial class createuserblogandblogvotetable
>>>>>>>> f79621b394ebb8a026d7ccfa967b56a71b1ed6e1:Migrations/20240503041345_create user, blog and blog vote table .Designer.cs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GroupCoursework.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("blogContent")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<DateOnly>("blogCreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("blogImageUrl")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("text");

                    b.Property<string>("blogTitle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("text");

                    b.Property<DateOnly>("blogUpdatedAt")
                        .HasColumnType("date");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("GroupCoursework.Models.BlogVote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<bool>("IsVote")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("VoteId");

                    b.HasIndex("BlogId");

                    b.HasIndex("UserId");

                    b.ToTable("BlogVotes");
                });

            modelBuilder.Entity("GroupCoursework.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsUserDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GroupCoursework.Models.Blog", b =>
                {
                    b.HasOne("GroupCoursework.Models.User", "user")
                        .WithMany("Blogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("GroupCoursework.Models.BlogVote", b =>
                {
                    b.HasOne("GroupCoursework.Models.Blog", "Blog")
<<<<<<<< HEAD:Migrations/20240503052041_creat tables.Designer.cs
                        .WithMany("BlogVotes")
========
                        .WithMany()
>>>>>>>> f79621b394ebb8a026d7ccfa967b56a71b1ed6e1:Migrations/20240503041345_create user, blog and blog vote table .Designer.cs
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GroupCoursework.Models.User", "User")
                        .WithMany("BlogVotes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");

                    b.Navigation("User");
                });

<<<<<<<< HEAD:Migrations/20240503052041_creat tables.Designer.cs
            modelBuilder.Entity("GroupCoursework.Models.Blog", b =>
                {
                    b.Navigation("BlogVotes");
                });

========
>>>>>>>> f79621b394ebb8a026d7ccfa967b56a71b1ed6e1:Migrations/20240503041345_create user, blog and blog vote table .Designer.cs
            modelBuilder.Entity("GroupCoursework.Models.User", b =>
                {
                    b.Navigation("BlogVotes");

                    b.Navigation("Blogs");
                });
#pragma warning restore 612, 618
        }
    }
}
